ID - Addressed Issues with 4DVD Logo and Time Series Menu
dafrenchyman/4dvd pull request #40
Opened 2019-12-01 01:56 UTC by zaydor

I tried something a bit different to try to get the 4DVD logo showing up. And also addressed formatting issues with the Close button from the last pull request.

2019-12-04 06:13 UTC, dafrenchyman commented
I'll get to this PR later in the week. Pretty busy right now.

2019-12-06 05:05 UTC, dafrenchyman requested changes
You are very close. Please address the comments mentioned in this PR.

2019-12-06 05:05 UTC, dafrenchyman commented on src/app/timeseries-menu.component.html
> +    <u>Pressure Layers</u>
This one addition (_Pressure Layers_ text) seems to be messing up the size of the pop-up window and adding arrow bars to it (to scroll up and down the window).

2019-12-06 05:05 UTC, dafrenchyman commented on src/app/timeseries-menu.component.html
> +      Close Time Series
I don't like _Close Time Series_ button. I prefer how you put an X in the top right corner of the navbar to close that menu. Please do that here too, just add an X in the upper right corner of this window. I don't think we really need a close button, but that would look better.

2019-12-06 05:05 UTC, dafrenchyman commented on src/app/timeseries-menu.component.html
> +    <p>Latitude: {{ this._model.settings.CurrGridBoxLat }}</p>
I like adding the Lat/Lon to this window. Nice job.

2019-12-06 05:05 UTC, dafrenchyman commented on src/app/settings.ts
> +  StringToArray(str): string {
I like the fact that you did this function. But the function/methods name should match what it's doing. It's not doing a `StringToArray`, it's actually generating the title.

2019-12-19 23:56 UTC, zaydor commented
Addressed your comments, also moved the pressure layer checkboxes to the right of the graph as I thought it looked a bit cleaner than below the graph.

2019-12-25 06:16 UTC, dafrenchyman commented
Opps,.. just noticed this. I'll get to it. Sorry.

2019-12-28 17:27 UTC, dafrenchyman requested changes
I just tested it and it still doesn't work.
When I check-mark more datasets to display it adds the arrow bars because the legend above it grows and grows as we add more datasets into it.

2019-12-28 17:37 UTC, zaydor commented
Yeah, apologies. I am aware of that issue. It was working before without extending the popup box, but for whatever reason it turned into a single list. Working on a fix for it but was not able to test it while out of town. Will be fixed by Monday.

2020-01-19 17:46 UTC, dafrenchyman commented
Hi Zaydor, 
I'm finally getting around to testing this, and the time series screen still doesn't work right.
I think we need to go about this a completely different way:
- You should split your work into different PRs. The other stuff you've done: The logo, the changes to removing `mrsharky_` would all have been easily approved if they were in their own PRs. When you write PRs they should be for changing/adding one thing, especially in this case when those would have been easy to approve.
- I do like what you've done with the time series, the only problem is that the window re-renders when it adds the legend in. I think you have two options here: 
-- Remove the legend, and make our buttons the legend instead. Color code our legend buttons to match what they look like in the graph.
-- Keep the legend buttons on the bottom for now, but keep your lat/lon stuff. Eventually I think it would be beneficial to move to a different charting library (https://c3js.org/)

2020-01-20 01:22 UTC, closed without merging