ID - Time Series Menu Changes
dafrenchyman/4dvd pull request #57
Opened 2020-04-17 11:13 UTC by zaydor

Last part of splitting LogoAndTimeSeries3 branch.

Features include:
* Y-Axis title
* Save Graph button is now a material button
* Initial graph line color is darker
* Exit graph button
* Swap "Default" with "Single Level" (Note: Not able to swap easily with the "Legend" in the time series chart due to limitations with ngx-charts, so that is the only place where default would still be found)
* Cleaner time series chart tool tips

2020-04-19 18:16 UTC, dafrenchyman requested changes
Please address the comments (both adding `TODO` and fixing the code with the `JSON.parse()` recommendations.

2020-04-19 18:16 UTC, dafrenchyman commented on src/app/settings.ts
> +  GenerateSimpleTitle(str): string {
I'm not a fan of this hack.

2020-04-19 18:16 UTC, dafrenchyman commented on src/app/timeseries-menu.component.ts
> +  getToolTipData(jsonString) {
This whole substring split stuff looks really hacky.

2020-04-19 18:16 UTC, dafrenchyman commented on src/app/timeseries-menu.component.ts
> +  chartToolTipDate(jsonString) {
I'm not sure why you have a json string here. But you shouldn't be parsing the json as a string. You instead should just convert it to a class/object and get the elements out of it normally:
`JSON.parse(jsonString)`

2020-04-19 18:16 UTC, dafrenchyman commented on src/app/timeseries-menu.component.ts
> +  getToolTipData(jsonString) {
Read me below statement. Use
`JSON.parse(jsonString)` instead, much cleaner.

2020-04-19 18:16 UTC, dafrenchyman commented on src/app/settings.ts
> +    if (str === "Default") {
I'm not a fan of this hack either. We should just change this in the database instead.

2020-04-19 18:16 UTC, dafrenchyman commented on src/app/settings.ts
> +    if (str === "Default") {
If you want to keep it here, add a `TODO:` comment so we know to eventually fix this in the database.

2020-04-19 18:16 UTC, dafrenchyman commented on src/app/settings.ts
> +  GenerateSimpleTitle(str): string {
If you want to keep it here, add a `TODO:` comment so we know to eventually fix this in the database.

2020-04-19 18:16 UTC, dafrenchyman commented on src/app/timeseries-menu.component.ts
> +    @Inject(MAT_DIALOG_DATA) public data: any
Is this how you're getting the "model" object in the "HTML" that you're passing to the below functions? It's pretty cool.

2020-05-06 05:23 UTC, dafrenchyman commented
The branch still doesn't seem to be re-based off of master. Github won't let me merge it, but it doesn't have any issues with your other branch: https://github.com/dafrenchyman/4dvd/pull/61 

Did you run :
`git fetch`
`git checkout master`
`git pull`
`git status`  Make sure it says your up to date with origin/master
`git checkout TSMenuChanges`
`git rebase master`
Hopefully I have it all correct up there. You'll then most likely need to need to correct changes go through code changes and stuff.
`git status` should tell you what you need to do next. You may need to inspect some code and update it to match between what you have and what was in master. You may need to add some changes etc....

2020-05-13 23:21 UTC, zaydor commented
I followed your instructions and did some research on my own and I think I figured it out/know what to look for on sourcetree now. Let me know if it is working.. I appreciate your patience, as I am learning this as I go. Thanks!

2020-05-20 06:26 UTC, dafrenchyman approved these changes

2020-05-20 06:38 UTC, dafrenchyman requested changes
I still can't merge it.

2020-05-20 07:11 UTC, dafrenchyman commented
It still wasn't re-based correctly. I went ahead and did it myself,... but I don't know if I messed up your code in the process. Please review the changes.

2020-05-20 07:11 UTC, dafrenchyman approved these changes

2020-05-20 20:53 UTC, zaydor commented
Looks good to me.

2020-05-20 20:53 UTC, merged